// packages/app-react/src/components/layout/app_topbar.tsx
import { ReactNode } from "react";

export function AppTopbar(props: {
    children?: ReactNode;
    teil?: ReactNode;
}) {
    return (
        <>
            <div className='border-b'>
                <div className='flex h-16 items-center px-4'>
                    <slot name='header'></slot>
                    <nav className='flex items-center space-x-4 lg:space-x-6'>
                        {props.children}
                    </nav>
                    { props.teil }
                </div>
            </div>
        </>
    );
}

// packages/app/src/components/layouts/AppTopbar.vue
<script setup lang="ts">
</script>

<template>
    <div class="border-b">
        <div class="flex h-16 items-center px-4">
            <slot name="header"></slot>
            <nav class="flex items-center space-x-4 lg:space-x-6">
                <slot></slot>
            </nav>
            <slot name="flooter">

            </slot>
        </div>
    </div>
</template>

<style></style>
