// packages/app-react/src/pages/admin/auth.tsx
import { createFileRoute, Link, Outlet } from "@tanstack/react-router";

export const Route = createFileRoute("/admin/auth")({
    component: AuthCompoent,
});

function AuthCompoent() {
    const { t } = useTranslation();

    return (
        <>
            <div className='container'>
                <div className='inline-flex h-10 items-center justify-center rounded-md bg-muted p-1 text-muted-foreground'>
                    <Link
                        to='/admin/auth/users'
                        activeProps={{
                            className:
                                "bg-background text-foreground shadow-sm",
                        }}
                        className='inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50'
                    >
                        {t("admin.categoies.items.user")}
                    </Link>
                    <Link
                        to='/admin/auth/roles'
                        activeProps={{
                            className:
                                "bg-background text-foreground shadow-sm",
                        }}
                        className='inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50'
                    >
                        {t("admin.categoies.items.roles")}
                    </Link>
                </div>
                <div className='mt-2 ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2'>
                    <Outlet></Outlet>
                </div>
            </div>
        </>
    );
}

// packages/app/src/pages/admin/auth.vue
<template>
    <div>
        <div class="inline-flex h-10 items-center justify-center rounded-md bg-muted p-1 text-muted-foreground">
            <RouterLink to="/admin/auth" exact-active-class="bg-background text-foreground shadow-sm"
                class="inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50">
                {{ t('admin.categoies.items.user') }}
            </RouterLink>
            <RouterLink to="/admin/auth/roles" exact-active-class="bg-background text-foreground shadow-sm"
                class="inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50">
                {{ t('admin.categoies.items.roles') }}
            </RouterLink>
        </div>
        <div
            class="mt-2 ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2">
            <RouterView v-slot="{ Component }">
                <Transition>
                    <component :is="Component"></component>
                </Transition>
            </RouterView>
        </div>
    </div>
</template>

<script setup lang="ts">
const { t } = useI18n();
</script>
